Neos:
  Neos:
    Ui:
      resources:
        javascript:
          Beromir.ToggleEditor:
            resource: resource://Beromir.ToggleEditor/Public/Plugin.js
        stylesheets:
          Beromir.ToggleEditor:
            resource: resource://Beromir.ToggleEditor/Public/Plugin.css
    userInterface:
      translation:
        autoInclude:
          Beromir.ToggleEditor:
            - Main
